apiVersion: v1
kind: Namespace
metadata:
  name: circumplex-ai
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: circumplex-ai
  name: vllm-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-rolebinding
  namespace: circumplex-ai
subjects:
- kind: ServiceAccount
  name: vllm-service
  namespace: circumplex-ai
roleRef:
  kind: Role
  name: vllm-role
  apiGroup: rbac.authorization.k8s.io
