apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: circumplex-ai
data:
  redis.conf: |
    bind 127.0.0.1 10.0.0.5
    port 0
    tls-port 6379
    tls-cert-file /certs/redis.crt
    tls-key-file /certs/redis.key
    tls-ca-cert-file /certs/ca.crt
    tls-auth-clients yes
    tls-protocols "TLSv1.2 TLSv1.3"

    # ACLs
    ACL SETUSER appuser on >${REDIS_PASSWORD} +@read +@write resetchannels &session:* ~session:* -@admin -@dangerous
    ACL SETUSER default off

